name = "Synchray"
uuid = "4dacfd78-acba-4c5e-8916-e152d0905f35"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.0"

[deps]
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Swizzling = "00000000-0000-4000-b000-202512210000"
