[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
AxisKeysExtra = "b7a0d2b7-1990-46dc-b5dd-87820ecd1b09"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MakieExtra = "54e234d5-9986-40d8-815f-a5e42de435f6"
PyFormattedStrings = "5f89f4a4-a228-4886-b223-c468a82ed5b9"
RectiGrids = "8ac6971d-971d-971d-971d-971d5ab1a71a"
Synchray = "4dacfd78-acba-4c5e-8916-e152d0905f35"
